const EQUATIONS = [
  { name: 'ISA Temperature', eq: 'T(h) = T0 - L·h' },
  { name: 'ISA Pressure', eq: 'P(h) = P0 · (T(h)/T0)^(g0/(R·L))' },
  { name: 'ISA Density', eq: 'ρ(h) = P(h) / (R·T(h))' },
  { name: 'Dynamic Pressure', eq: 'q = ½·ρ·V²' },
  { name: 'Lift', eq: 'L = Cl·q·S' },
  { name: 'Induced Drag Coeff.', eq: 'Cdi = Cl² / (π·e·AR)' },
  { name: 'Drag Coefficient', eq: 'Cd = Cd0 + Cdi' },
  { name: 'Drag', eq: 'D = Cd·q·S' },
  { name: 'Stall Speed', eq: 'Vstall = √(2W / (ρ·S·Clmax))' },
  { name: 'Power Required', eq: 'Preq = D·V' },
  { name: 'Power Available', eq: 'Pavail = Pmotor · ηprop(ρ)' },
  { name: 'Rate of Climb', eq: 'ROC = (Pavail − Preq) / W' },
  { name: 'Wing Loading', eq: 'W/S' },
  { name: 'Power Loading', eq: 'Pmotor / m' },
  { name: 'Lift-to-Drag Ratio', eq: 'L/D = Cl / Cd' },
  { name: 'Endurance (electric)', eq: 'E = Ebatt·(1−reserve) / (Preq/ηprop)' },
  { name: 'Range', eq: 'R = V · E' },
];

const PARAMS = [
  { name: 'Mass / Payload', influence: 'Direct, ↑ mass → ↑ required lift → ↑ induced drag & power required', type: 'Input' },
  { name: 'Wing Area', influence: 'Direct, ↑ S → ↓ wing loading → ↓ stall speed, ↑ structure/drag area', type: 'Input' },
  { name: 'Wingspan / Aspect Ratio', influence: 'Indirect via AR, ↑ AR → ↓ induced drag → ↑ L/D', type: 'Input / Derived' },
  { name: 'Air Density', influence: 'Direct, ↓ ρ with altitude → ↑ required Cl at fixed speed → ↑ induced drag', type: 'Derived (from altitude)' },
  { name: 'Cl_max / Cd0 / Oswald e', influence: 'Direct, define the drag polar and stall boundary', type: 'Input' },
  { name: 'Battery Energy', influence: 'Direct, ↑ energy → ↑ endurance, no effect on lift/drag', type: 'Input' },
  { name: 'Motor Power / Prop Efficiency', influence: 'Direct, sets power available; degrades with altitude via ρ', type: 'Input' },
  { name: 'Cruise Speed', influence: 'Direct, sets the operating point on the drag polar at every altitude', type: 'Input' },
  { name: 'Wing / Power Loading', influence: 'Derived summary indicators of climb & stall margin', type: 'Derived, used as ML feature' },
];

export default function AboutPage() {
  return (
    <div className="max-w-3xl">
      <div className="eyebrow mb-2">Page 10</div>
      <h1 className="font-display text-3xl font-semibold mb-6">About &amp; Methodology</h1>

      <section className="mb-10">
        <h2 className="font-display text-lg font-semibold mb-3 text-cyan">What this platform does</h2>
        <p className="text-sm text-muted leading-relaxed">
          This is a physics-informed machine learning platform for predicting the flight envelope
          of a fixed-wing electric mini-UAV: minimum/maximum/recommended operating altitude, service
          and absolute ceiling, rate of climb, range, endurance, power required, lift, drag, and a
          rule-based safety classification. It runs two parallel prediction paths — a transparent
          physics engine (ISA atmosphere + classical aircraft-performance equations) and an ML
          surrogate model trained on data generated by that same physics engine — and shows both,
          side by side, so the ML output can be audited against ground truth.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="font-display text-lg font-semibold mb-3 text-cyan">Why synthetic data</h2>
        <p className="text-sm text-muted leading-relaxed mb-3">
          No real UAV flight-test dataset was used. Real telemetry at this granularity — systematic
          sweeps of altitude, power, and lift across many configurations — is operationally
          restricted and not available for a research prototype. Instead, the dataset was generated
          by sampling 6,000 UAV design configurations within realistic bounds for a 7–25&nbsp;kg
          electric fixed-wing UAV class, and computing their ground-truth flight envelope with the
          physics engine. This is standard practice for early-stage physics-informed surrogate
          modeling in aerospace research.
        </p>
        <p className="text-sm text-muted leading-relaxed">
          <span className="text-amber">Limitation:</span> the ML model can only be as good as the
          physics equations that generated its training data. It does not capture turbulence, gust
          response, manufacturing tolerances, sensor noise, or off-nominal propeller behaviour —
          effects that real flight-test data would reveal. Treat all outputs as engineering-estimate
          guidance for early design exploration, not as certified airworthiness data.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="font-display text-lg font-semibold mb-3 text-cyan">Why "recommended altitude" isn't the average</h2>
        <p className="text-sm text-muted leading-relaxed">
          The recommended altitude is <em>not</em> (min + max) / 2. It's selected by scoring every
          feasible altitude below the service ceiling on a weighted combination of aerodynamic
          efficiency (L/D), climb-rate safety margin, power margin, and an endurance proxy — then
          picking the highest-scoring altitude. Because the design holds cruise airspeed fixed
          across the sweep, required Cl rises with altitude (thinner air), so parasite drag falls
          while induced drag rises — producing a genuine minimum-power altitude that shifts with
          the aircraft's actual configuration. The simple midpoint is still shown separately, labelled
          "mean altitude", for reference only.
        </p>
      </section>

      <section className="mb-10">
        <h2 className="font-display text-lg font-semibold mb-3 text-cyan">Parameters &amp; their influence on altitude</h2>
        <div className="panel overflow-x-auto">
          <table className="w-full text-xs font-mono min-w-[600px]">
            <thead>
              <tr className="text-muted uppercase border-b border-border">
                <th className="text-left py-2.5 px-3">Parameter</th>
                <th className="text-left py-2.5 px-3">Influence on altitude / envelope</th>
                <th className="text-left py-2.5 px-3">ML role</th>
              </tr>
            </thead>
            <tbody>
              {PARAMS.map((p, i) => (
                <tr key={i} className="border-b border-border/50">
                  <td className="py-2 px-3 text-text">{p.name}</td>
                  <td className="py-2 px-3 text-muted">{p.influence}</td>
                  <td className="py-2 px-3 text-cyan">{p.type}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="font-display text-lg font-semibold mb-3 text-cyan">Formula sheet</h2>
        <div className="panel overflow-x-auto">
          <table className="w-full text-xs font-mono min-w-[500px]">
            <tbody>
              {EQUATIONS.map((e, i) => (
                <tr key={i} className="border-b border-border/50">
                  <td className="py-2 px-3 text-text w-1/3">{e.name}</td>
                  <td className="py-2 px-3 text-cyan">{e.eq}</td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </section>

      <section className="mb-10">
        <h2 className="font-display text-lg font-semibold mb-3 text-cyan">Implemented vs. assumed vs. future work</h2>
        <div className="grid sm:grid-cols-3 gap-4 text-sm">
          <div className="panel p-4">
            <div className="eyebrow text-green mb-2">Implemented</div>
            <ul className="text-muted text-xs space-y-1.5 list-disc list-inside">
              <li>Full ISA troposphere atmosphere model</li>
              <li>Steady-level-flight lift/drag/power equations</li>
              <li>Excess-power climb &amp; ceiling theory</li>
              <li>Multi-output ML surrogate, 7 models compared</li>
              <li>Permutation + native feature importance</li>
              <li>PDF/CSV export, batch CSV prediction, PWA</li>
            </ul>
          </div>
          <div className="panel p-4">
            <div className="eyebrow text-amber mb-2">Synthetic Assumptions</div>
            <ul className="text-muted text-xs space-y-1.5 list-disc list-inside">
              <li>Design parameter sampling bounds (7–25 kg class)</li>
              <li>Empirical propeller-efficiency-vs-altitude curve</li>
              <li>Fixed 20% battery reserve for endurance</li>
              <li>No wind, gust, or turbulence modeling</li>
              <li>Single fixed cruise Cl-max airfoil family</li>
            </ul>
          </div>
          <div className="panel p-4">
            <div className="eyebrow text-cyan mb-2">Future Enhancements</div>
            <ul className="text-muted text-xs space-y-1.5 list-disc list-inside">
              <li>SHAP values for per-prediction explanations</li>
              <li>Partial dependence plots per feature</li>
              <li>CatBoost in the model comparison</li>
              <li>Wind/gust-perturbed envelope</li>
              <li>Validation against real flight-test logs</li>
            </ul>
          </div>
        </div>
      </section>
    </div>
  );
}
